services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  users-service:
    build: ./users-service
    container_name: users-service
    env_file:
      - .env
    environment:
      - PORT=${USERS_SERVICE_PORT}
    depends_on:
      - mongo
    ports:
      - "${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}"

  content-service:
    build: ./content-service
    container_name: content-service
    env_file:
      - .env
    environment:
      - PORT=${CONTENT_SERVICE_PORT}
    depends_on:
      - mongo
    ports:
      - "${CONTENT_SERVICE_PORT}:${CONTENT_SERVICE_PORT}"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    env_file:
      - .env
    environment:
      - PORT=${NOTIFICATION_SERVICE_PORT}
    depends_on:
      - mongo
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file:
      - .env
    environment:
      - PORT=${API_GATEWAY_PORT}
    depends_on:
      - users-service
      - content-service
      - notification-service
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"

volumes:
  mongo_data:
