services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile

    container_name: users-service
    env_file:
      - .env
    environment:
      JWT_SECRET: "dev-secret-min-32-chars-0123456789ABCDEF"
      REFRESH_SECRET: "dev-refresh-min-32-chars-0123456789ABCDEF"

    depends_on:
      - mongo
    ports:
      - "${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}"

  content-service:
    build:
      context: .
      dockerfile: content-service/Dockerfile

    container_name: content-service
    env_file:
      - .env
    environment:
      JWT_SECRET: "dev-secret-min-32-chars-0123456789ABCDEF"

    depends_on:
      - mongo
    ports:
      - "${CONTENT_SERVICE_PORT}:${CONTENT_SERVICE_PORT}"

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile

    container_name: notification-service
    env_file:
      - .env
    environment:
      JWT_SECRET: "dev-secret-min-32-chars-0123456789ABCDEF"

    depends_on:
      - mongo
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file:
      - .env
    environment:
      JWT_SECRET: "dev-secret-min-32-chars-0123456789ABCDEF"

    depends_on:
      - users-service
      - content-service
      - notification-service
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"

volumes:
  mongo_data:
